name: pdtable-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - typing_extensions # for typing.Protocol back-port to python 3.7
# OPTIONAL
  - openpyxl
  - pint
# BUILD+TEST
  - pytest
  - coverage
  - pytest-cov
  - black
  - flake8
  - flake8-black
  - flake8-comprehensions
  - sphinx
# DEV
  - twine
  - jupyter
  - jupyterlab
  - jupytext
